### ISSUE TITLE
ph lightlist crashes

### ISSUE THREAD

**Issue by hannseman** [ebaauw/homebridge-hue-utils#4]
Hi, thanks for the great work you've made with homebridge-hue. I'm trying to run `ph lightlist` but it crashes with the following traceback:

```
$ ph lightlist
ph lightlist: error: TypeError: this.getId is not a function
    at Main.lightlist (/usr/lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/cli/ph.js:514:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I'm running version `0.4.9` on homebridge-hue-utils with node `8.11.1`

**Comment by hannseman** [comment]
Weird I stopped getting this issue now after manually specifying the username to the `ph` command. After this I can no longer see this error even when running `ph` without the `--username` flag with the `.ph`-file present. Closing this as it was probably something weird with my setup.

**Comment by ebaauw** [comment]
It appears to be a bug alright.  I occurs only when newly creating a resourcelink for the lightlist, not when updating an existing resourcelink.  The error occurs just after creating the resourcelink, so that explains you don't see it anymore.
